// Run once: node server/scripts/seedMeals.js
// Clears the meals collection and re-inserts the full meal catalog.

require("dotenv").config({ path: require("path").join(__dirname, "../.env") });
const mongoose = require("mongoose");
const Meal     = require("../models/Meal");

function norm(allergens) {
  if (!allergens) return [];
  if (Array.isArray(allergens)) return allergens.map(String).map(s => s.trim()).filter(Boolean);
  if (typeof allergens === "string") return allergens.split(",").map(s => s.trim()).filter(Boolean);
  return [];
}

const RAW_MEALS = [
  // ──────────────────────────────── BREAKFAST ──────────────────────────────
  { name: "Jowar Ambil (250ml fermented drink)", type: "breakfast", calorie_range: "200-300", calories: 210, protein: 6, carbs: 30, fats: 4, fiber: 4, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Sattu Drink (40g roasted gram flour)", type: "breakfast", calorie_range: "200-300", calories: 220, protein: 12, carbs: 30, fats: 4, fiber: 6, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Steamed Dhokla (150g)", type: "breakfast", calorie_range: "200-300", calories: 230, protein: 10, carbs: 36, fats: 5, fiber: 4, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Ragi Porridge (40g + milk 100ml)", type: "breakfast", calorie_range: "200-300", calories: 240, protein: 9, carbs: 38, fats: 6, fiber: 4, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Milk"] },
  { name: "Besan Chilla (80g batter)", type: "breakfast", calorie_range: "200-300", calories: 250, protein: 12, carbs: 30, fats: 8, fiber: 6, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "2 Idli + Sambar", type: "breakfast", calorie_range: "200-300", calories: 260, protein: 9, carbs: 46, fats: 3, fiber: 4, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Vegetable Poha (60g raw)", type: "breakfast", calorie_range: "200-300", calories: 265, protein: 7, carbs: 42, fats: 8, fiber: 4, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Nuts"] },
  { name: "Ghugni (150g)", type: "breakfast", calorie_range: "200-300", calories: 280, protein: 12, carbs: 42, fats: 7, fiber: 9, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Spices"] },
  { name: "Bajra Raab (250ml)", type: "breakfast", calorie_range: "200-300", calories: 285, protein: 8, carbs: 40, fats: 7, fiber: 6, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Boiled Sweet Potato (200g) + Mint Chutney", type: "breakfast", calorie_range: "200-300", calories: 290, protein: 4, carbs: 48, fats: 1, fiber: 7, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Egg White Bhurji (4 whites) + Spinach", type: "breakfast", calorie_range: "200-300", calories: 235, protein: 28, carbs: 8, fats: 10, fiber: 4, vegetarian: "No", diabetic_friendly: "Yes", allergens: ["Egg"] },
  { name: "Sprouted Moong Salad (300g) + Roti", type: "breakfast", calorie_range: "300-400", calories: 310, protein: 16, carbs: 48, fats: 6, fiber: 8, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Gluten"] },
  { name: "Greek Yogurt Bowl (300g) + Nuts (15g)", type: "breakfast", calorie_range: "300-400", calories: 315, protein: 22, carbs: 18, fats: 12, fiber: 3, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Milk", "Nuts"] },
  { name: "Thalipeeth (2 pcs) + Curd", type: "breakfast", calorie_range: "300-400", calories: 360, protein: 13, carbs: 48, fats: 12, fiber: 8, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Milk"] },
  { name: "Handvo (150g)", type: "breakfast", calorie_range: "300-400", calories: 380, protein: 12, carbs: 52, fats: 14, fiber: 6, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Upma (200g) + Coconut Chutney", type: "breakfast", calorie_range: "300-400", calories: 385, protein: 10, carbs: 56, fats: 14, fiber: 4, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Gluten"] },
  { name: "Idiyappam (3 pcs) + Vegetable Kurma", type: "breakfast", calorie_range: "300-400", calories: 390, protein: 8, carbs: 62, fats: 8, fiber: 3, vegetarian: "Yes", diabetic_friendly: "No", allergens: [] },
  { name: "Paneer Bhurji (100g) + 1 Phulka", type: "breakfast", calorie_range: "300-400", calories: 395, protein: 24, carbs: 28, fats: 18, fiber: 2, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Milk", "Gluten"] },
  { name: "Aloo Paratha (2 small) + Green Chutney", type: "breakfast", calorie_range: "300-400", calories: 420, protein: 12, carbs: 60, fats: 12, fiber: 4, vegetarian: "Yes", diabetic_friendly: "No", allergens: ["Gluten"] },
  { name: "Egg Omelette (2 eggs) + Toast", type: "breakfast", calorie_range: "300-400", calories: 430, protein: 18, carbs: 30, fats: 20, fiber: 2, vegetarian: "No", diabetic_friendly: "No", allergens: ["Egg", "Gluten"] },
  { name: "Ven Pongal (200g)", type: "breakfast", calorie_range: "400-500", calories: 450, protein: 14, carbs: 68, fats: 12, fiber: 4, vegetarian: "Yes", diabetic_friendly: "No", allergens: [] },
  { name: "Masala Dosa + Sambar", type: "breakfast", calorie_range: "400-500", calories: 460, protein: 12, carbs: 65, fats: 15, fiber: 6, vegetarian: "Yes", diabetic_friendly: "No", allergens: [] },
  { name: "Roti (2) + Aloo Tori Sabzi", type: "breakfast", calorie_range: "400-500", calories: 460, protein: 9, carbs: 72, fats: 14, fiber: 6, vegetarian: "Yes", diabetic_friendly: "No", allergens: ["Gluten"] },
  { name: "Masala Chole + Bread Toast (2 slices)", type: "breakfast", calorie_range: "400-500", calories: 470, protein: 14, carbs: 72, fats: 14, fiber: 10, vegetarian: "Yes", diabetic_friendly: "No", allergens: ["Gluten"] },
  { name: "Poha + Kadala Curry", type: "breakfast", calorie_range: "400-500", calories: 480, protein: 14, carbs: 70, fats: 16, fiber: 8, vegetarian: "Yes", diabetic_friendly: "No", allergens: [] },
  { name: "Chola Kulhe (1 cup + 2 bread)", type: "breakfast", calorie_range: "400-500", calories: 490, protein: 16, carbs: 78, fats: 14, fiber: 12, vegetarian: "Yes", diabetic_friendly: "No", allergens: ["Gluten"] },
  { name: "Sprouted Moong (250g) + Roasted Chana", type: "breakfast", calorie_range: "400-500", calories: 485, protein: 30, carbs: 68, fats: 10, fiber: 14, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Moong Dal Chilla (120g batter) + Paneer", type: "breakfast", calorie_range: "500-600", calories: 520, protein: 40, carbs: 38, fats: 28, fiber: 8, vegetarian: "Yes", diabetic_friendly: "No", allergens: ["Milk"] },
  { name: "Vegetable Millet Upma (large bowl)", type: "breakfast", calorie_range: "500-600", calories: 520, protein: 18, carbs: 76, fats: 12, fiber: 8, vegetarian: "Yes", diabetic_friendly: "No", allergens: [] },
  { name: "Grilled Cheese Sandwich (2 pcs)", type: "breakfast", calorie_range: "500-600", calories: 540, protein: 22, carbs: 52, fats: 24, fiber: 3, vegetarian: "Yes", diabetic_friendly: "No", allergens: ["Milk", "Gluten"] },
  { name: "Zunka + Bhakri (2 pcs)", type: "breakfast", calorie_range: "500-600", calories: 540, protein: 18, carbs: 68, fats: 18, fiber: 8, vegetarian: "Yes", diabetic_friendly: "No", allergens: [] },
  { name: "Fish Omelette (2 eggs + fish 80g)", type: "breakfast", calorie_range: "500-600", calories: 548, protein: 38, carbs: 8, fats: 36, fiber: 2, vegetarian: "No", diabetic_friendly: "No", allergens: ["Egg", "Seafood"] },
  { name: "Stuffed Methi Paratha (2 pcs) + Curd", type: "breakfast", calorie_range: "500-600", calories: 560, protein: 16, carbs: 75, fats: 18, fiber: 8, vegetarian: "Yes", diabetic_friendly: "No", allergens: ["Milk", "Gluten"] },
  { name: "Egg Bhurji (3 eggs) + 2 Phulka", type: "breakfast", calorie_range: "500-600", calories: 560, protein: 25, carbs: 40, fats: 28, fiber: 4, vegetarian: "No", diabetic_friendly: "No", allergens: ["Egg", "Gluten"] },
  { name: "Stuffed Paratha (2 pcs) + Curd", type: "breakfast", calorie_range: "500-600", calories: 595, protein: 32, carbs: 56, fats: 28, fiber: 6, vegetarian: "Yes", diabetic_friendly: "No", allergens: ["Milk", "Gluten"] },
  { name: "Greek Curd (300g) + Chia + Almonds", type: "breakfast", calorie_range: "500-600", calories: 540, protein: 32, carbs: 22, fats: 36, fiber: 7, vegetarian: "Yes", diabetic_friendly: "No", allergens: ["Milk", "Nuts"] },
  { name: "Grilled Chicken (220g) + Vegetables", type: "breakfast", calorie_range: "500-600", calories: 550, protein: 52, carbs: 18, fats: 30, fiber: 5, vegetarian: "No", diabetic_friendly: "Yes", allergens: [] },
  { name: "Kala Chana (300g boiled) + Curd", type: "breakfast", calorie_range: "500-600", calories: 580, protein: 40, carbs: 70, fats: 16, fiber: 16, vegetarian: "Yes", diabetic_friendly: "No", allergens: ["Milk"] },
  { name: "Paneer Paratha (4 pcs) + Curd", type: "breakfast", calorie_range: "600-700", calories: 620, protein: 28, carbs: 72, fats: 25, fiber: 7, vegetarian: "Yes", diabetic_friendly: "No", allergens: ["Milk", "Gluten"] },
  { name: "Aloo Puri + Chole (plate)", type: "breakfast", calorie_range: "600-700", calories: 650, protein: 14, carbs: 90, fats: 24, fiber: 7, vegetarian: "Yes", diabetic_friendly: "No", allergens: ["Gluten"] },
  { name: "Masala Paratha (4 pcs) + Achaar", type: "breakfast", calorie_range: "600-700", calories: 670, protein: 26, carbs: 92, fats: 26, fiber: 6, vegetarian: "Yes", diabetic_friendly: "No", allergens: ["Gluten"] },
  { name: "Chole Bhature (1 piece + chole)", type: "breakfast", calorie_range: "600-700", calories: 680, protein: 14, carbs: 92, fats: 28, fiber: 6, vegetarian: "Yes", diabetic_friendly: "No", allergens: ["Gluten"] },
  { name: "Paneer Keema Bhurji + Toast (2 slices)", type: "breakfast", calorie_range: "600-700", calories: 688, protein: 38, carbs: 48, fats: 40, fiber: 4, vegetarian: "Yes", diabetic_friendly: "No", allergens: ["Milk", "Gluten"] },
  { name: "Chicken Keema (100g) + 2 Roti", type: "breakfast", calorie_range: "600-700", calories: 690, protein: 38, carbs: 56, fats: 28, fiber: 6, vegetarian: "No", diabetic_friendly: "No", allergens: ["Gluten"] },
  { name: "Chole Puri (full plate)", type: "breakfast", calorie_range: "600-700", calories: 695, protein: 18, carbs: 96, fats: 30, fiber: 12, vegetarian: "Yes", diabetic_friendly: "No", allergens: ["Gluten"] },
  { name: "Paneer Tikka (200g) + Salad + Roti", type: "breakfast", calorie_range: "700-800", calories: 716, protein: 44, carbs: 18, fats: 52, fiber: 5, vegetarian: "Yes", diabetic_friendly: "No", allergens: ["Milk", "Gluten"] },

  // ──────────────────────────────── LUNCH ──────────────────────────────────
  { name: "Moong Dal (150g cooked) + Brown Rice (100g) + Lauki Sabzi", type: "lunch", calorie_range: "200-300", calories: 292, protein: 14, carbs: 46, fats: 6, fiber: 8, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Masoor Dal (150g cooked) + Phulka + Bhindi", type: "lunch", calorie_range: "200-300", calories: 298, protein: 13, carbs: 44, fats: 7, fiber: 8, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Gluten"] },
  { name: "Sambar (200ml) + Red Rice (100g) + Beans Poriyal", type: "lunch", calorie_range: "200-300", calories: 286, protein: 10, carbs: 48, fats: 5, fiber: 7, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Rasam (200ml) + Rice (100g) + Cabbage Stir Fry", type: "lunch", calorie_range: "200-300", calories: 284, protein: 9, carbs: 50, fats: 4, fiber: 6, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Odisha Dalma (150g cooked) + Rice (100g)", type: "lunch", calorie_range: "200-300", calories: 289, protein: 12, carbs: 44, fats: 6, fiber: 8, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Gujarati Thin Kadhi (200ml) + Brown Rice (100g)", type: "lunch", calorie_range: "200-300", calories: 285, protein: 8, carbs: 46, fats: 6, fiber: 3, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Milk"] },
  { name: "Light Egg Curry (1 egg) + Rice (100g)", type: "lunch", calorie_range: "200-300", calories: 285, protein: 14, carbs: 38, fats: 10, fiber: 2, vegetarian: "No", diabetic_friendly: "Yes", allergens: ["Egg"] },
  { name: "Light Rohu Fish Curry (80g) + Rice (100g)", type: "lunch", calorie_range: "200-300", calories: 290, protein: 20, carbs: 36, fats: 8, fiber: 2, vegetarian: "No", diabetic_friendly: "Yes", allergens: ["Seafood"] },
  { name: "Rajma (180g cooked) + Brown Rice (150g)", type: "lunch", calorie_range: "300-400", calories: 372, protein: 17, carbs: 64, fats: 7, fiber: 10, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Chole (180g cooked) + Phulka (60g flour)", type: "lunch", calorie_range: "300-400", calories: 376, protein: 18, carbs: 66, fats: 9, fiber: 11, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Gluten"] },
  { name: "Chicken Curry (120g cooked) + Brown Rice (120g)", type: "lunch", calorie_range: "300-400", calories: 369, protein: 30, carbs: 52, fats: 12, fiber: 4, vegetarian: "No", diabetic_friendly: "Yes", allergens: [] },
  { name: "Egg Curry (2 eggs) + Rice (120g)", type: "lunch", calorie_range: "300-400", calories: 365, protein: 22, carbs: 50, fats: 14, fiber: 3, vegetarian: "No", diabetic_friendly: "Yes", allergens: ["Egg"] },
  { name: "Fish Curry (Rohu 120g) + Rice (120g)", type: "lunch", calorie_range: "300-400", calories: 378, protein: 30, carbs: 54, fats: 11, fiber: 3, vegetarian: "No", diabetic_friendly: "Yes", allergens: ["Seafood"] },
  { name: "Paneer Bhurji (80g) + Phulka (60g flour)", type: "lunch", calorie_range: "300-400", calories: 368, protein: 22, carbs: 44, fats: 18, fiber: 5, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Milk", "Gluten"] },
  { name: "Bengali Musur Dal (200g) + Rice (150g) + Pumpkin Sabzi", type: "lunch", calorie_range: "300-400", calories: 362, protein: 14, carbs: 64, fats: 7, fiber: 8, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Chicken Curry (150g) + Brown Rice (150g)", type: "lunch", calorie_range: "400-500", calories: 445, protein: 35, carbs: 60, fats: 14, fiber: 4, vegetarian: "No", diabetic_friendly: "Yes", allergens: [] },
  { name: "Fish Curry (Rohu 150g) + Rice (150g)", type: "lunch", calorie_range: "400-500", calories: 448, protein: 34, carbs: 58, fats: 14, fiber: 3, vegetarian: "No", diabetic_friendly: "Yes", allergens: ["Seafood"] },
  { name: "Paneer Bhurji (120g) + Phulka (60g) + Salad", type: "lunch", calorie_range: "400-500", calories: 458, protein: 26, carbs: 48, fats: 20, fiber: 6, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Milk", "Gluten"] },
  { name: "Rajma (220g) + Brown Rice (150g)", type: "lunch", calorie_range: "400-500", calories: 462, protein: 19, carbs: 70, fats: 8, fiber: 12, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Chole (220g) + Rice (150g)", type: "lunch", calorie_range: "400-500", calories: 465, protein: 20, carbs: 72, fats: 12, fiber: 11, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Bengali Shorshe Rohu (150g) + Rice (150g)", type: "lunch", calorie_range: "400-500", calories: 468, protein: 34, carbs: 60, fats: 18, fiber: 3, vegetarian: "No", diabetic_friendly: "Yes", allergens: ["Seafood"] },
  { name: "Kerala Fish Curry (Sardine 150g) + Red Rice", type: "lunch", calorie_range: "400-500", calories: 472, protein: 36, carbs: 62, fats: 16, fiber: 4, vegetarian: "No", diabetic_friendly: "Yes", allergens: ["Seafood"] },
  { name: "Gujarati Undhiyu (250g) + Phulka", type: "lunch", calorie_range: "400-500", calories: 456, protein: 14, carbs: 60, fats: 14, fiber: 11, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Gluten"] },
  { name: "Baingan Bharta (250g) + Phulka (60g)", type: "lunch", calorie_range: "400-500", calories: 448, protein: 11, carbs: 56, fats: 16, fiber: 10, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Gluten"] },
  { name: "Light Mutton Curry (120g lean) + Brown Rice (150g)", type: "lunch", calorie_range: "400-500", calories: 462, protein: 32, carbs: 60, fats: 18, fiber: 3, vegetarian: "No", diabetic_friendly: "Yes", allergens: [] },
  { name: "Mutton Curry (150g lean) + Rice (180g)", type: "lunch", calorie_range: "500-600", calories: 565, protein: 38, carbs: 72, fats: 22, fiber: 3, vegetarian: "No", diabetic_friendly: "Yes", allergens: [] },
  { name: "Pomfret Curry (180g) + Rice (180g)", type: "lunch", calorie_range: "500-600", calories: 558, protein: 40, carbs: 70, fats: 18, fiber: 3, vegetarian: "No", diabetic_friendly: "Yes", allergens: ["Seafood"] },
  { name: "Chicken Thali (150g + Phulka + Dal)", type: "lunch", calorie_range: "500-600", calories: 572, protein: 45, carbs: 68, fats: 20, fiber: 9, vegetarian: "No", diabetic_friendly: "Yes", allergens: ["Gluten"] },
  { name: "Vegetarian Thali (Paneer 150g + Rice + Dal)", type: "lunch", calorie_range: "500-600", calories: 568, protein: 32, carbs: 80, fats: 22, fiber: 10, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Milk"] },
  { name: "Prawn Curry (180g) + Rice (180g)", type: "lunch", calorie_range: "500-600", calories: 578, protein: 42, carbs: 74, fats: 20, fiber: 3, vegetarian: "No", diabetic_friendly: "Yes", allergens: ["Seafood"] },
  { name: "Curd Rice (300g) + Vegetable Fry", type: "lunch", calorie_range: "500-600", calories: 542, protein: 14, carbs: 78, fats: 14, fiber: 4, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Milk"] },
  { name: "Dal Tadka (250g) + Phulka (90g flour)", type: "lunch", calorie_range: "500-600", calories: 548, protein: 22, carbs: 82, fats: 16, fiber: 13, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Gluten"] },
  { name: "Bengali Fish Thali (Rohu 180g + 200g Rice + Dal + Sabzi)", type: "lunch", calorie_range: "600-700", calories: 620, protein: 45, carbs: 94, fats: 20, fiber: 9, vegetarian: "No", diabetic_friendly: "Yes", allergens: ["Seafood"] },
  { name: "Chicken Thali (200g + Phulka + Rajma)", type: "lunch", calorie_range: "600-700", calories: 638, protein: 55, carbs: 82, fats: 24, fiber: 11, vegetarian: "No", diabetic_friendly: "Yes", allergens: ["Gluten"] },
  { name: "Gujarati Thali (Undhiyu + Dal + Phulka + Rice)", type: "lunch", calorie_range: "600-700", calories: 652, protein: 22, carbs: 98, fats: 18, fiber: 12, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Gluten"] },
  { name: "Paneer Butter Masala (200g) + Phulka + Rice", type: "lunch", calorie_range: "700-800", calories: 718, protein: 34, carbs: 98, fats: 34, fiber: 8, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Milk", "Gluten"] },
  { name: "Hyderabadi Chicken Biryani (350g) + Raita", type: "lunch", calorie_range: "700-800", calories: 742, protein: 52, carbs: 96, fats: 30, fiber: 5, vegetarian: "No", diabetic_friendly: "Yes", allergens: ["Milk"] },
  { name: "Prawn Curry (220g) + Rice (200g) + Vegetable Stir Fry", type: "lunch", calorie_range: "700-800", calories: 758, protein: 55, carbs: 96, fats: 26, fiber: 7, vegetarian: "No", diabetic_friendly: "Yes", allergens: ["Seafood"] },
  { name: "Rajma Chawal Large Plate (300g + 250g + Salad)", type: "lunch", calorie_range: "700-800", calories: 728, protein: 30, carbs: 130, fats: 14, fiber: 18, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Chole Bhature (2 Medium, controlled oil)", type: "lunch", calorie_range: "700-800", calories: 762, protein: 24, carbs: 110, fats: 32, fiber: 10, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Gluten"] },
  { name: "Chole Bhature Large (2 Large Pcs + Extra Chole)", type: "lunch", calorie_range: "800-900", calories: 790, protein: 28, carbs: 110, fats: 32, fiber: 15, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Gluten", "Milk"] },
  { name: "Kerala Fish Thali (Sardine 220g + Red Rice + Dal + Thoran)", type: "lunch", calorie_range: "800-900", calories: 808, protein: 46, carbs: 88, fats: 32, fiber: 6, vegetarian: "No", diabetic_friendly: "Yes", allergens: ["Seafood", "Milk"] },
  { name: "Prawn Masala (220g) + Rice (220g) + Papad", type: "lunch", calorie_range: "800-900", calories: 820, protein: 48, carbs: 86, fats: 34, fiber: 4, vegetarian: "No", diabetic_friendly: "Yes", allergens: ["Seafood"] },
  { name: "Paneer Butter Masala Large (250g) + Naan (90g)", type: "lunch", calorie_range: "800-900", calories: 832, protein: 32, carbs: 78, fats: 42, fiber: 6, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Milk", "Gluten"] },
  { name: "Bengali Hilsa Fish Curry (200g) + Rice (220g) + Sabzi", type: "lunch", calorie_range: "800-900", calories: 845, protein: 50, carbs: 82, fats: 36, fiber: 4, vegetarian: "No", diabetic_friendly: "Yes", allergens: ["Seafood"] },
  { name: "Mutton Biryani (300g) + Raita", type: "lunch", calorie_range: "800-900", calories: 858, protein: 52, carbs: 88, fats: 36, fiber: 5, vegetarian: "No", diabetic_friendly: "Yes", allergens: ["Milk"] },
  { name: "Vegetable Biryani Large (350g) + Raita", type: "lunch", calorie_range: "800-900", calories: 865, protein: 24, carbs: 116, fats: 28, fiber: 14, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Milk"] },
  { name: "Chole Bhature Extra Large (3 Pcs + Extra Chole)", type: "lunch", calorie_range: "900-1000", calories: 878, protein: 30, carbs: 122, fats: 35, fiber: 17, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Gluten", "Milk"] },
  { name: "Bengali Fish Thali Large (250g Rohu + 250g Rice + Dal + 2 Sabzi)", type: "lunch", calorie_range: "900-1000", calories: 895, protein: 52, carbs: 92, fats: 40, fiber: 6, vegetarian: "No", diabetic_friendly: "Yes", allergens: ["Seafood"] },
  { name: "Chicken Thali Large (250g + Rice + Dal + Roti + Sabzi)", type: "lunch", calorie_range: "900-1000", calories: 920, protein: 58, carbs: 92, fats: 38, fiber: 7, vegetarian: "No", diabetic_friendly: "Yes", allergens: ["Gluten"] },
  { name: "Mutton Curry Large (220g) + Rice (250g) + Phulka", type: "lunch", calorie_range: "900-1000", calories: 938, protein: 55, carbs: 96, fats: 42, fiber: 6, vegetarian: "No", diabetic_friendly: "Yes", allergens: ["Gluten"] },
  { name: "Paneer Tikka Masala (300g) + Naan (120g) + Rice (100g)", type: "lunch", calorie_range: "900-1000", calories: 952, protein: 36, carbs: 106, fats: 44, fiber: 9, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Milk", "Gluten"] },
  { name: "Paneer Makhani Large (350g) + Naan (120g) + Rice (100g)", type: "lunch", calorie_range: "1000-1100", calories: 1020, protein: 38, carbs: 118, fats: 46, fiber: 10, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Milk", "Gluten"] },
  { name: "Rajma Chawal Full Plate (350g + 300g + Salad + Papad)", type: "lunch", calorie_range: "1000-1100", calories: 1045, protein: 32, carbs: 130, fats: 40, fiber: 18, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Chicken Biryani Full Plate (450g) + Raita + Mirchi Salan", type: "lunch", calorie_range: "1000-1100", calories: 1065, protein: 60, carbs: 104, fats: 46, fiber: 8, vegetarian: "No", diabetic_friendly: "Yes", allergens: ["Milk"] },
  { name: "Mutton Rogan Josh (300g) + Rice (250g) + Naan", type: "lunch", calorie_range: "1000-1100", calories: 1080, protein: 65, carbs: 108, fats: 48, fiber: 8, vegetarian: "No", diabetic_friendly: "Yes", allergens: ["Gluten"] },
  { name: "Vegetarian Thali Full (Paneer + Rajma + Dal + 3 Phulka + Rice)", type: "lunch", calorie_range: "1000-1100", calories: 1095, protein: 42, carbs: 118, fats: 46, fiber: 12, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Milk", "Gluten"] },

  // ──────────────────────────────── DINNER ──────────────────────────────────
  { name: "Moong Dal Clear Broth (300g, strained) + Steamed Spinach (150g) + 1 Small Phulka (30g flour)", type: "dinner", calorie_range: "200-300", calories: 230, protein: 14, carbs: 26, fats: 5, fiber: 8, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Grilled Rohu (120g) + Lauki-Tomato Stew (180g) + 150g Steamed Rice", type: "dinner", calorie_range: "200-300", calories: 260, protein: 26, carbs: 10, fats: 14, fiber: 4, vegetarian: "No", diabetic_friendly: "Yes", allergens: ["Seafood"] },
  { name: "Egg White Bhurji (3 whites + 1 whole egg) + Sautéed Palak (150g) + 1 Small Phulka (30g flour)", type: "dinner", calorie_range: "200-300", calories: 255, protein: 24, carbs: 8, fats: 12, fiber: 4, vegetarian: "No", diabetic_friendly: "Yes", allergens: ["Egg"] },
  { name: "Gujarati Thin Kadhi (300ml, low-fat) + 1 Small Phulka (30g flour)", type: "dinner", calorie_range: "200-300", calories: 210, protein: 10, carbs: 20, fats: 9, fiber: 2, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Milk"] },
  { name: "Sprouted Moong Warm Salad (220g) + Lemon + 1 Small Ragi Roti (30g flour)", type: "dinner", calorie_range: "200-300", calories: 250, protein: 18, carbs: 32, fats: 6, fiber: 10, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Kerala Vegetable Stew (Coconut light, 250g) + 2 Small Appam", type: "dinner", calorie_range: "200-300", calories: 280, protein: 8, carbs: 24, fats: 18, fiber: 5, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Andhra Tomato Rasam (350ml) + Beans Poriyal (150g) + 120g Brown Rice", type: "dinner", calorie_range: "200-300", calories: 225, protein: 9, carbs: 28, fats: 6, fiber: 7, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Grilled Chicken (150g) + Stir Fry Zucchini (150g) + 120g Brown Rice", type: "dinner", calorie_range: "300-400", calories: 360, protein: 36, carbs: 10, fats: 18, fiber: 3, vegetarian: "No", diabetic_friendly: "Yes", allergens: [] },
  { name: "Paneer Tikka (150g) + Mint Chutney + 1 Small Jowar Roti (30g flour)", type: "dinner", calorie_range: "300-400", calories: 390, protein: 26, carbs: 12, fats: 28, fiber: 2, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Milk"] },
  { name: "Bengali Light Fish Jhol (Rohu 150g, minimal oil) + 150g Steamed Rice", type: "dinner", calorie_range: "300-400", calories: 320, protein: 30, carbs: 8, fats: 16, fiber: 2, vegetarian: "No", diabetic_friendly: "Yes", allergens: ["Seafood"] },
  { name: "Adai (2 small, 150g batter, no chutney)", type: "dinner", calorie_range: "300-400", calories: 340, protein: 18, carbs: 42, fats: 10, fiber: 8, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Sundal (250g boiled chana, tempered light) + 1 Small Ragi Roti (30g flour)", type: "dinner", calorie_range: "300-400", calories: 370, protein: 19, carbs: 54, fats: 8, fiber: 12, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Egg Curry (2 eggs, light gravy) + 1 Small Phulka (30g flour)", type: "dinner", calorie_range: "300-400", calories: 330, protein: 20, carbs: 8, fats: 24, fiber: 2, vegetarian: "No", diabetic_friendly: "Yes", allergens: ["Egg"] },
  { name: "Jowar Ambil (Fermented, 400ml) + Light Vegetable Stir Fry", type: "dinner", calorie_range: "300-400", calories: 310, protein: 12, carbs: 48, fats: 6, fiber: 7, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Grilled Chicken (180g) + Sautéed Mixed Vegetables (200g) + 120g Brown Rice", type: "dinner", calorie_range: "400-500", calories: 430, protein: 44, carbs: 16, fats: 22, fiber: 5, vegetarian: "No", diabetic_friendly: "Yes", allergens: [] },
  { name: "Kerala Seer Fish Curry (180g, light coconut) + Beans Thoran (150g) + 120g Red Rice", type: "dinner", calorie_range: "400-500", calories: 460, protein: 38, carbs: 18, fats: 26, fiber: 6, vegetarian: "No", diabetic_friendly: "Yes", allergens: ["Seafood"] },
  { name: "Paneer Tikka (200g) + Stir Fry Capsicum (150g) + 1 Small Jowar Roti (30g flour)", type: "dinner", calorie_range: "400-500", calories: 480, protein: 32, carbs: 14, fats: 34, fiber: 4, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Milk"] },
  { name: "Egg Masala (3 eggs, reduced oil) + Cabbage Peas Stir Fry (180g) + 1 Small Phulka (30g flour)", type: "dinner", calorie_range: "400-500", calories: 470, protein: 28, carbs: 20, fats: 32, fiber: 5, vegetarian: "No", diabetic_friendly: "Yes", allergens: ["Egg"] },
  { name: "Sundal Bowl (300g boiled chana) + Cucumber Salad + 1 Small Ragi Roti (30g flour)", type: "dinner", calorie_range: "400-500", calories: 420, protein: 22, carbs: 62, fats: 10, fiber: 14, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Maharashtrian Zunka (Besan 120g cooked) + Bhindi Stir Fry (150g) + 1 Small Bajra Bhakri (40g flour)", type: "dinner", calorie_range: "400-500", calories: 450, protein: 24, carbs: 36, fats: 22, fiber: 9, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Bengali Light Chingri (Prawn 180g, minimal oil) + Lauki Sabzi (180g) + 150g Steamed Rice", type: "dinner", calorie_range: "400-500", calories: 480, protein: 42, carbs: 16, fats: 30, fiber: 4, vegetarian: "No", diabetic_friendly: "Yes", allergens: ["Seafood"] },
  { name: "Adai (2 medium) + Coconut Chutney (15g, controlled)", type: "dinner", calorie_range: "400-500", calories: 440, protein: 20, carbs: 48, fats: 18, fiber: 9, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Gujarati Handvo (200g, baked) + Mint Chutney", type: "dinner", calorie_range: "400-500", calories: 470, protein: 18, carbs: 52, fats: 18, fiber: 7, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Hyderabadi Egg Keema (3 eggs scrambled) + Spinach (150g) + 1 Small Phulka (30g flour)", type: "dinner", calorie_range: "400-500", calories: 460, protein: 30, carbs: 10, fats: 34, fiber: 4, vegetarian: "No", diabetic_friendly: "Yes", allergens: ["Egg"] },
  { name: "Grilled Chicken (220g) + Broccoli-Carrot Stir Fry (200g) + 120g Brown Rice", type: "dinner", calorie_range: "500-600", calories: 540, protein: 52, carbs: 18, fats: 30, fiber: 6, vegetarian: "No", diabetic_friendly: "Yes", allergens: [] },
  { name: "Kerala Seer Fish (220g, light coconut gravy) + Cabbage Thoran (180g) + 120g Red Rice", type: "dinner", calorie_range: "500-600", calories: 560, protein: 44, carbs: 22, fats: 34, fiber: 7, vegetarian: "No", diabetic_friendly: "Yes", allergens: ["Seafood"] },
  { name: "Paneer Tikka (220g) + Palak Stir Fry (200g) + 1 Small Jowar Roti (30g flour)", type: "dinner", calorie_range: "500-600", calories: 590, protein: 36, carbs: 18, fats: 40, fiber: 6, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Milk"] },
  { name: "Egg Curry (4 eggs, reduced oil) + Beans-Carrot Sabzi (200g) + 1 Small Phulka (30g flour)", type: "dinner", calorie_range: "500-600", calories: 560, protein: 32, carbs: 22, fats: 38, fiber: 6, vegetarian: "No", diabetic_friendly: "Yes", allergens: ["Egg"] },
  { name: "Maharashtrian Zunka (150g, besan cooked) + Bhindi (200g) + 1 Small Bajra Bhakri (40g flour)", type: "dinner", calorie_range: "500-600", calories: 520, protein: 28, carbs: 40, fats: 28, fiber: 11, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Bengali Chingri (220g prawn, light mustard gravy) + Lauki (200g) + 150g Steamed Rice", type: "dinner", calorie_range: "500-600", calories: 580, protein: 50, carbs: 18, fats: 38, fiber: 5, vegetarian: "No", diabetic_friendly: "Yes", allergens: ["Seafood"] },
  { name: "Adai (3 medium) + Mint Chutney (20g)", type: "dinner", calorie_range: "500-600", calories: 520, protein: 26, carbs: 62, fats: 20, fiber: 12, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Gujarati Handvo (220g, baked) + Cucumber Raita (100g)", type: "dinner", calorie_range: "500-600", calories: 550, protein: 20, carbs: 58, fats: 22, fiber: 8, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Hyderabadi Chicken Keema (200g) + Stir Fry Capsicum (200g) + 1 Small Phulka (30g flour)", type: "dinner", calorie_range: "500-600", calories: 590, protein: 48, carbs: 16, fats: 32, fiber: 5, vegetarian: "No", diabetic_friendly: "Yes", allergens: [] },
  { name: "Palak Paneer (220g, light) + Sautéed Mushroom (150g) + 1 Small Phulka (30g flour)", type: "dinner", calorie_range: "500-600", calories: 570, protein: 30, carbs: 18, fats: 42, fiber: 6, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Milk"] },
  { name: "Tandoori Chicken (250g) + Grilled Vegetables (250g) + 120g Brown Rice", type: "dinner", calorie_range: "600-700", calories: 610, protein: 60, carbs: 24, fats: 36, fiber: 7, vegetarian: "No", diabetic_friendly: "Yes", allergens: [] },
  { name: "Kerala Seer Fish Roast (250g) + Cabbage Thoran (200g) + 120g Red Rice", type: "dinner", calorie_range: "600-700", calories: 670, protein: 50, carbs: 20, fats: 46, fiber: 6, vegetarian: "No", diabetic_friendly: "Yes", allergens: ["Seafood"] },
  { name: "Paneer Tikka (250g) + Palak Mushroom Stir Fry (250g) + 1 Small Jowar Roti (30g flour)", type: "dinner", calorie_range: "600-700", calories: 690, protein: 40, carbs: 20, fats: 50, fiber: 8, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Milk"] },
  { name: "Hyderabadi Chicken Keema (250g) + Sautéed Beans (250g) + 120g Brown Rice", type: "dinner", calorie_range: "600-700", calories: 680, protein: 56, carbs: 18, fats: 48, fiber: 6, vegetarian: "No", diabetic_friendly: "Yes", allergens: [] },
  { name: "Egg Masala (5 eggs, controlled oil) + Spinach (200g) + 1 Small Ragi Roti (30g flour)", type: "dinner", calorie_range: "600-700", calories: 650, protein: 38, carbs: 18, fats: 48, fiber: 5, vegetarian: "No", diabetic_friendly: "Yes", allergens: ["Egg"] },
  { name: "Maharashtrian Mutton Sukka (220g, lean) + Bhindi Fry (200g) + 1 Small Bajra Bhakri (40g flour)", type: "dinner", calorie_range: "600-700", calories: 700, protein: 52, carbs: 21, fats: 50, fiber: 7, vegetarian: "No", diabetic_friendly: "No", allergens: ["Nut"] },
  { name: "Gujarati Zunka (180g, besan) + Cabbage Peas (250g) + 1 Small Jowar Roti (30g flour)", type: "dinner", calorie_range: "600-700", calories: 620, protein: 32, carbs: 48, fats: 31, fiber: 12, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Bengali Mustard Prawn (250g) + Lauki (250g) + 150g Steamed Rice", type: "dinner", calorie_range: "600-700", calories: 690, protein: 56, carbs: 16, fats: 50, fiber: 6, vegetarian: "No", diabetic_friendly: "Yes", allergens: ["Seafood"] },
  { name: "Adai (3 large) + Coconut Chutney (25g, controlled)", type: "dinner", calorie_range: "600-700", calories: 610, protein: 30, carbs: 72, fats: 22, fiber: 14, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Palak Paneer (250g) + Mushroom Stir Fry (200g) + 1 Small Phulka (30g flour)", type: "dinner", calorie_range: "600-700", calories: 660, protein: 34, carbs: 22, fats: 48, fiber: 7, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Milk"] },
  { name: "Butter Chicken (300g, moderate oil) + 2 Phulka (60g flour)", type: "dinner", calorie_range: "700-900", calories: 760, protein: 60, carbs: 58, fats: 40, fiber: 6, vegetarian: "No", diabetic_friendly: "No", allergens: ["Gluten"] },
  { name: "Hyderabadi Chicken Biryani (400g, controlled oil)", type: "dinner", calorie_range: "700-900", calories: 780, protein: 52, carbs: 92, fats: 30, fiber: 5, vegetarian: "No", diabetic_friendly: "No", allergens: [] },
  { name: "Paneer Butter Masala (300g) + 2 Phulka", type: "dinner", calorie_range: "700-900", calories: 820, protein: 38, carbs: 60, fats: 50, fiber: 6, vegetarian: "Yes", diabetic_friendly: "No", allergens: ["Milk", "Gluten"] },
  { name: "Kerala Seer Fish Fry (280g) + Cabbage Thoran (250g) + 120g Red Rice", type: "dinner", calorie_range: "700-900", calories: 730, protein: 60, carbs: 22, fats: 48, fiber: 6, vegetarian: "No", diabetic_friendly: "No", allergens: ["Seafood"] },
  { name: "Bengali Ilish Bhapa (250g Hilsa, mustard steamed) + Lauki (250g) + 150g Steamed Rice", type: "dinner", calorie_range: "700-900", calories: 800, protein: 52, carbs: 18, fats: 58, fiber: 5, vegetarian: "No", diabetic_friendly: "No", allergens: ["Seafood"] },
  { name: "Mutton Rogan (250g lean) + 2 Phulka", type: "dinner", calorie_range: "700-900", calories: 850, protein: 58, carbs: 52, fats: 58, fiber: 5, vegetarian: "No", diabetic_friendly: "No", allergens: ["Gluten"] },
  { name: "Gujarati Undhiyu (350g) + Kadhi (250ml) + 1 Jowar Roti", type: "dinner", calorie_range: "700-900", calories: 720, protein: 21, carbs: 88, fats: 34, fiber: 14, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Milk"] },
  { name: "Prawn Masala (300g) + Sautéed Beans (250g) + 120g Brown Rice", type: "dinner", calorie_range: "700-900", calories: 840, protein: 70, carbs: 20, fats: 58, fiber: 7, vegetarian: "No", diabetic_friendly: "Yes", allergens: ["Seafood"] },
  { name: "Chicken Tikka (300g) + Stir Fry Vegetables (300g) + 120g Brown Rice", type: "dinner", calorie_range: "700-900", calories: 720, protein: 66, carbs: 28, fats: 42, fiber: 8, vegetarian: "No", diabetic_friendly: "Yes", allergens: [] },
  { name: "Palak Paneer (300g) + Mushroom Stir Fry (250g) + 1 Small Phulka (30g flour)", type: "dinner", calorie_range: "700-900", calories: 780, protein: 42, carbs: 24, fats: 58, fiber: 8, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Milk"] },
  { name: "Butter Chicken (350g) + 2 Butter Naan (100g flour total)", type: "dinner", calorie_range: "900-1000", calories: 940, protein: 68, carbs: 78, fats: 60, fiber: 6, vegetarian: "No", diabetic_friendly: "No", allergens: ["Gluten"] },
  { name: "Hyderabadi Chicken Biryani (500g cooked, moderate oil) + Raita (200g)", type: "dinner", calorie_range: "900-1000", calories: 920, protein: 60, carbs: 110, fats: 38, fiber: 5, vegetarian: "No", diabetic_friendly: "No", allergens: ["Milk"] },
  { name: "Mutton Rogan (300g lean) + 2 Phulka (60g flour)", type: "dinner", calorie_range: "900-1000", calories: 960, protein: 70, carbs: 52, fats: 72, fiber: 5, vegetarian: "No", diabetic_friendly: "No", allergens: ["Gluten"] },
  { name: "Paneer Butter Masala (350g) + 2 Butter Naan", type: "dinner", calorie_range: "900-1000", calories: 880, protein: 46, carbs: 84, fats: 70, fiber: 6, vegetarian: "Yes", diabetic_friendly: "No", allergens: ["Milk", "Gluten"] },
  { name: "Kerala Seer Fish Fry (320g) + 150g Red Rice", type: "dinner", calorie_range: "900-1000", calories: 910, protein: 68, carbs: 62, fats: 58, fiber: 5, vegetarian: "No", diabetic_friendly: "No", allergens: ["Seafood"] },
  { name: "Bengali Ilish Bhapa (300g) + 180g Rice", type: "dinner", calorie_range: "900-1000", calories: 950, protein: 62, carbs: 68, fats: 70, fiber: 5, vegetarian: "No", diabetic_friendly: "No", allergens: ["Seafood"] },
  { name: "Prawn Masala (350g) + 150g Rice", type: "dinner", calorie_range: "900-1000", calories: 980, protein: 76, carbs: 62, fats: 72, fiber: 5, vegetarian: "No", diabetic_friendly: "No", allergens: ["Seafood"] },
  { name: "Chicken Tikka (350g) + 2 Phulka", type: "dinner", calorie_range: "900-1000", calories: 900, protein: 80, carbs: 52, fats: 56, fiber: 5, vegetarian: "No", diabetic_friendly: "No", allergens: ["Gluten"] },
  { name: "Gujarati Undhiyu (400g) + Kadhi (300ml) + 1 Jowar Roti", type: "dinner", calorie_range: "900-1000", calories: 910, protein: 28, carbs: 120, fats: 42, fiber: 18, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Milk"] },
  { name: "Palak Paneer (350g) + Mushroom Stir Fry (300g) + 1 Small Phulka (30g flour)", type: "dinner", calorie_range: "900-1000", calories: 900, protein: 48, carbs: 30, fats: 72, fiber: 9, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Milk"] },
  { name: "Butter Chicken (400g) + 2 Butter Naan (120g flour total)", type: "dinner", calorie_range: "1000-1100", calories: 1040, protein: 76, carbs: 92, fats: 72, fiber: 6, vegetarian: "No", diabetic_friendly: "No", allergens: ["Gluten"] },
  { name: "Hyderabadi Chicken Biryani (600g cooked) + Raita (200g)", type: "dinner", calorie_range: "1000-1100", calories: 1030, protein: 70, carbs: 128, fats: 42, fiber: 7, vegetarian: "No", diabetic_friendly: "No", allergens: ["Milk"] },
  { name: "Mutton Rogan (350g lean) + 2 Butter Naan", type: "dinner", calorie_range: "1000-1100", calories: 1080, protein: 82, carbs: 84, fats: 82, fiber: 5, vegetarian: "No", diabetic_friendly: "No", allergens: ["Gluten"] },
  { name: "Paneer Butter Masala (400g) + 2 Butter Naan", type: "dinner", calorie_range: "1000-1100", calories: 1100, protein: 54, carbs: 92, fats: 86, fiber: 6, vegetarian: "Yes", diabetic_friendly: "No", allergens: ["Milk", "Gluten"] },
  { name: "Kerala Seer Fish Fry (350g) + 200g Red Rice", type: "dinner", calorie_range: "1000-1100", calories: 1010, protein: 78, carbs: 88, fats: 62, fiber: 7, vegetarian: "No", diabetic_friendly: "No", allergens: ["Seafood"] },
  { name: "Bengali Ilish Bhapa (350g) + 200g Rice", type: "dinner", calorie_range: "1000-1100", calories: 1060, protein: 70, carbs: 82, fats: 82, fiber: 5, vegetarian: "No", diabetic_friendly: "No", allergens: ["Seafood"] },
  { name: "Prawn Masala (400g) + 180g Rice", type: "dinner", calorie_range: "1000-1100", calories: 1090, protein: 88, carbs: 84, fats: 86, fiber: 5, vegetarian: "No", diabetic_friendly: "No", allergens: ["Seafood"] },
  { name: "Chicken Tikka (400g) + 2 Phulka", type: "dinner", calorie_range: "1000-1100", calories: 1000, protein: 92, carbs: 52, fats: 66, fiber: 5, vegetarian: "No", diabetic_friendly: "No", allergens: ["Gluten"] },
  { name: "Gujarati Undhiyu (450g) + Kadhi (350ml) + 1 Jowar Roti", type: "dinner", calorie_range: "1000-1100", calories: 1020, protein: 32, carbs: 140, fats: 50, fiber: 20, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Milk"] },
  { name: "Palak Paneer (400g) + Mushroom Stir Fry (350g) + 1 Small Phulka (30g flour)", type: "dinner", calorie_range: "1000-1100", calories: 1000, protein: 56, carbs: 38, fats: 80, fiber: 10, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Milk"] },

  // ──────────────────────────────── SNACKS ──────────────────────────────────
  { name: "Roasted Chana", type: "snacks", calorie_range: "120-180", calories: 150, protein: 8, carbs: 22, fats: 2, fiber: 6, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Sprouted Moong Salad", type: "snacks", calorie_range: "150-210", calories: 180, protein: 10, carbs: 28, fats: 2, fiber: 7, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Boiled Kala Chana", type: "snacks", calorie_range: "160-220", calories: 190, protein: 10, carbs: 32, fats: 2, fiber: 8, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Chana + Onion + Lemon", type: "snacks", calorie_range: "160-220", calories: 190, protein: 10, carbs: 30, fats: 2, fiber: 8, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Peanut + Gur", type: "snacks", calorie_range: "220-300", calories: 260, protein: 10, carbs: 20, fats: 16, fiber: 4, vegetarian: "Yes", diabetic_friendly: "No", allergens: ["Peanuts"] },
  { name: "Roasted Makhana", type: "snacks", calorie_range: "100-150", calories: 120, protein: 4, carbs: 15, fats: 4, fiber: 2, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Makhana + Almonds", type: "snacks", calorie_range: "180-240", calories: 210, protein: 7, carbs: 18, fats: 12, fiber: 3, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Nuts"] },
  { name: "Muri + Peanut", type: "snacks", calorie_range: "150-220", calories: 190, protein: 6, carbs: 28, fats: 7, fiber: 3, vegetarian: "Yes", diabetic_friendly: "No", allergens: ["Peanuts"] },
  { name: "Muri + Chana", type: "snacks", calorie_range: "160-230", calories: 200, protein: 8, carbs: 30, fats: 3, fiber: 5, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Muri + Sprouts", type: "snacks", calorie_range: "180-250", calories: 220, protein: 9, carbs: 32, fats: 4, fiber: 6, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Sattu Drink", type: "snacks", calorie_range: "150-220", calories: 180, protein: 10, carbs: 28, fats: 2, fiber: 6, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Sattu + Yogurt", type: "snacks", calorie_range: "200-260", calories: 230, protein: 12, carbs: 30, fats: 6, fiber: 6, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Milk"] },
  { name: "Sweet Potato Chaat", type: "snacks", calorie_range: "180-240", calories: 210, protein: 4, carbs: 38, fats: 2, fiber: 6, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Boiled Corn", type: "snacks", calorie_range: "180-240", calories: 210, protein: 6, carbs: 30, fats: 3, fiber: 4, vegetarian: "Yes", diabetic_friendly: "No", allergens: [] },
  { name: "Boiled Potato (Black Salt)", type: "snacks", calorie_range: "160-220", calories: 190, protein: 4, carbs: 35, fats: 1, fiber: 4, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Fruit + Peanut Butter", type: "snacks", calorie_range: "200-260", calories: 230, protein: 7, carbs: 30, fats: 10, fiber: 5, vegetarian: "Yes", diabetic_friendly: "No", allergens: ["Peanuts"] },
  { name: "Apple + Peanut Butter", type: "snacks", calorie_range: "180-250", calories: 220, protein: 6, carbs: 25, fats: 12, fiber: 5, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Peanuts"] },
  { name: "Banana + Peanut Butter", type: "snacks", calorie_range: "250-320", calories: 290, protein: 10, carbs: 34, fats: 14, fiber: 4, vegetarian: "Yes", diabetic_friendly: "No", allergens: ["Peanuts"] },
  { name: "Guava + Black Salt", type: "snacks", calorie_range: "100-140", calories: 120, protein: 3, carbs: 22, fats: 1, fiber: 6, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Papaya Bowl", type: "snacks", calorie_range: "80-120", calories: 100, protein: 1, carbs: 24, fats: 0, fiber: 4, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Mixed Nuts", type: "snacks", calorie_range: "220-300", calories: 260, protein: 8, carbs: 16, fats: 20, fiber: 5, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Nuts"] },
  { name: "Almond + Dates", type: "snacks", calorie_range: "200-280", calories: 240, protein: 7, carbs: 28, fats: 12, fiber: 4, vegetarian: "Yes", diabetic_friendly: "No", allergens: ["Nuts"] },
  { name: "Walnut + Fruit", type: "snacks", calorie_range: "220-300", calories: 260, protein: 6, carbs: 26, fats: 18, fiber: 4, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Nuts"] },
  { name: "Til + Flax Seeds Mix", type: "snacks", calorie_range: "200-260", calories: 230, protein: 8, carbs: 20, fats: 14, fiber: 7, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Sesame"] },
  { name: "Peanut + Roasted Chana", type: "snacks", calorie_range: "220-300", calories: 260, protein: 10, carbs: 22, fats: 16, fiber: 7, vegetarian: "Yes", diabetic_friendly: "No", allergens: ["Peanuts"] },
  { name: "Sprouted Chana", type: "snacks", calorie_range: "180-240", calories: 210, protein: 11, carbs: 30, fats: 3, fiber: 8, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Sprouted Moong", type: "snacks", calorie_range: "180-250", calories: 220, protein: 12, carbs: 32, fats: 3, fiber: 8, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Boiled Egg", type: "snacks", calorie_range: "70-110", calories: 80, protein: 6, carbs: 1, fats: 5, fiber: 0, vegetarian: "No", diabetic_friendly: "Yes", allergens: ["Egg"] },
  { name: "Egg + Vegetable Salad", type: "snacks", calorie_range: "120-180", calories: 150, protein: 10, carbs: 5, fats: 8, fiber: 2, vegetarian: "No", diabetic_friendly: "Yes", allergens: ["Egg"] },
  { name: "Omelette (1 egg + veggies)", type: "snacks", calorie_range: "150-220", calories: 180, protein: 12, carbs: 5, fats: 10, fiber: 2, vegetarian: "No", diabetic_friendly: "Yes", allergens: ["Egg"] },
  { name: "Paneer Cutlet", type: "snacks", calorie_range: "180-240", calories: 210, protein: 14, carbs: 6, fats: 12, fiber: 0, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Milk"] },
  { name: "Paneer + Black Salt", type: "snacks", calorie_range: "200-260", calories: 230, protein: 14, carbs: 6, fats: 14, fiber: 0, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Milk"] },
  { name: "Paneer + Flax Seeds", type: "snacks", calorie_range: "200-260", calories: 230, protein: 14, carbs: 8, fats: 14, fiber: 4, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Milk"] },
  { name: "Hung Curd Dip + Veggies", type: "snacks", calorie_range: "180-240", calories: 210, protein: 12, carbs: 12, fats: 10, fiber: 6, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Milk"] },
  { name: "Yogurt + Fruit", type: "snacks", calorie_range: "150-220", calories: 180, protein: 9, carbs: 24, fats: 5, fiber: 3, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Milk"] },
  { name: "Chire + Yogurt", type: "snacks", calorie_range: "180-250", calories: 220, protein: 8, carbs: 40, fats: 4, fiber: 4, vegetarian: "Yes", diabetic_friendly: "No", allergens: ["Milk"] },
  { name: "Chire + Peanut", type: "snacks", calorie_range: "250-320", calories: 290, protein: 10, carbs: 45, fats: 12, fiber: 5, vegetarian: "Yes", diabetic_friendly: "No", allergens: ["Peanuts"] },
  { name: "Chire + Sprouts", type: "snacks", calorie_range: "220-300", calories: 260, protein: 10, carbs: 42, fats: 5, fiber: 7, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Poha + Vegetables", type: "snacks", calorie_range: "200-260", calories: 230, protein: 7, carbs: 38, fats: 5, fiber: 4, vegetarian: "Yes", diabetic_friendly: "No", allergens: [] },
  { name: "Upma + Vegetables", type: "snacks", calorie_range: "220-300", calories: 260, protein: 8, carbs: 40, fats: 6, fiber: 5, vegetarian: "Yes", diabetic_friendly: "No", allergens: ["Gluten"] },
  { name: "Vegetable Sandwich (Brown Bread)", type: "snacks", calorie_range: "200-280", calories: 240, protein: 9, carbs: 35, fats: 7, fiber: 5, vegetarian: "Yes", diabetic_friendly: "No", allergens: ["Gluten"] },
  { name: "Peanut Butter Toast", type: "snacks", calorie_range: "250-320", calories: 290, protein: 12, carbs: 30, fats: 14, fiber: 4, vegetarian: "Yes", diabetic_friendly: "No", allergens: ["Peanuts"] },
  { name: "Whole Wheat Toast + Egg", type: "snacks", calorie_range: "220-300", calories: 260, protein: 13, carbs: 28, fats: 10, fiber: 4, vegetarian: "No", diabetic_friendly: "No", allergens: ["Gluten", "Egg"] },
  { name: "Besan Chilla", type: "snacks", calorie_range: "180-240", calories: 210, protein: 10, carbs: 20, fats: 8, fiber: 4, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Moong Chilla", type: "snacks", calorie_range: "160-220", calories: 190, protein: 12, carbs: 18, fats: 6, fiber: 5, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Vegetable Soup", type: "snacks", calorie_range: "80-120", calories: 100, protein: 4, carbs: 18, fats: 2, fiber: 4, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Dal Soup", type: "snacks", calorie_range: "120-180", calories: 150, protein: 8, carbs: 22, fats: 3, fiber: 5, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Tomato Soup", type: "snacks", calorie_range: "90-130", calories: 110, protein: 3, carbs: 20, fats: 2, fiber: 4, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Buttermilk + Seeds", type: "snacks", calorie_range: "100-150", calories: 120, protein: 5, carbs: 10, fats: 4, fiber: 2, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Milk"] },
  { name: "Green Tea + Nuts", type: "snacks", calorie_range: "120-180", calories: 150, protein: 4, carbs: 8, fats: 10, fiber: 3, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Nuts"] },

  // ──────────────────────────────── DESSERT ──────────────────────────────────
  { name: "Chhena + Nolen Gur (Fresh Paneer + Jaggery)", type: "dessert", calorie_range: "180-240", calories: 210, protein: 12, carbs: 18, fats: 9, fiber: 0, vegetarian: "Yes", diabetic_friendly: "No", allergens: ["Milk"] },
  { name: "Curd + Honey", type: "dessert", calorie_range: "150-200", calories: 170, protein: 7, carbs: 22, fats: 5, fiber: 0, vegetarian: "Yes", diabetic_friendly: "No", allergens: ["Milk"] },
  { name: "Fruit Chaat", type: "dessert", calorie_range: "80-120", calories: 100, protein: 2, carbs: 24, fats: 0, fiber: 5, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Banana + Peanut", type: "dessert", calorie_range: "250-350", calories: 300, protein: 10, carbs: 35, fats: 14, fiber: 4, vegetarian: "Yes", diabetic_friendly: "No", allergens: ["Peanuts"] },
  { name: "Gur + Muri", type: "dessert", calorie_range: "120-180", calories: 150, protein: 3, carbs: 32, fats: 1, fiber: 2, vegetarian: "Yes", diabetic_friendly: "No", allergens: [] },
  { name: "Boiled Sweet Potato + Gur", type: "dessert", calorie_range: "160-220", calories: 190, protein: 3, carbs: 40, fats: 1, fiber: 5, vegetarian: "Yes", diabetic_friendly: "No", allergens: [] },
  { name: "Apple + Peanut Butter", type: "dessert", calorie_range: "180-250", calories: 220, protein: 6, carbs: 25, fats: 12, fiber: 5, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Peanuts"] },
  { name: "Dates + Milk", type: "dessert", calorie_range: "200-280", calories: 240, protein: 8, carbs: 35, fats: 6, fiber: 3, vegetarian: "Yes", diabetic_friendly: "No", allergens: ["Milk"] },
  { name: "Roasted Makhana + Gur", type: "dessert", calorie_range: "120-180", calories: 150, protein: 5, carbs: 18, fats: 5, fiber: 2, vegetarian: "Yes", diabetic_friendly: "No", allergens: ["Nuts"] },
  { name: "Oats + Milk + Honey", type: "dessert", calorie_range: "200-280", calories: 240, protein: 9, carbs: 35, fats: 6, fiber: 5, vegetarian: "Yes", diabetic_friendly: "No", allergens: ["Milk"] },
  { name: "Chire + Milk + Dates", type: "dessert", calorie_range: "220-300", calories: 260, protein: 8, carbs: 45, fats: 5, fiber: 4, vegetarian: "Yes", diabetic_friendly: "No", allergens: ["Milk"] },
  { name: "Sattu + Gur + Milk", type: "dessert", calorie_range: "250-350", calories: 300, protein: 12, carbs: 40, fats: 8, fiber: 7, vegetarian: "Yes", diabetic_friendly: "No", allergens: [] },
  { name: "Sprouted Moong + Honey", type: "dessert", calorie_range: "150-210", calories: 180, protein: 9, carbs: 28, fats: 2, fiber: 7, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Boiled Kala Chana + Gur", type: "dessert", calorie_range: "180-240", calories: 210, protein: 10, carbs: 35, fats: 2, fiber: 8, vegetarian: "Yes", diabetic_friendly: "No", allergens: [] },
  { name: "Papaya + Lemon + Honey", type: "dessert", calorie_range: "120-170", calories: 140, protein: 2, carbs: 30, fats: 0, fiber: 5, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Guava + Black Salt + Honey", type: "dessert", calorie_range: "100-150", calories: 120, protein: 3, carbs: 22, fats: 1, fiber: 6, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Pomegranate + Yogurt", type: "dessert", calorie_range: "150-200", calories: 180, protein: 6, carbs: 28, fats: 4, fiber: 3, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Milk"] },
  { name: "Mango + Chia", type: "dessert", calorie_range: "200-260", calories: 230, protein: 4, carbs: 35, fats: 8, fiber: 6, vegetarian: "Yes", diabetic_friendly: "No", allergens: [] },
  { name: "Banana + Yogurt + Honey", type: "dessert", calorie_range: "220-300", calories: 250, protein: 8, carbs: 38, fats: 5, fiber: 4, vegetarian: "Yes", diabetic_friendly: "No", allergens: ["Milk"] },
  { name: "Almond + Dates", type: "dessert", calorie_range: "200-280", calories: 240, protein: 7, carbs: 28, fats: 12, fiber: 5, vegetarian: "Yes", diabetic_friendly: "No", allergens: ["Nuts"] },
  { name: "Peanut + Gur Ball", type: "dessert", calorie_range: "250-350", calories: 290, protein: 10, carbs: 30, fats: 15, fiber: 4, vegetarian: "Yes", diabetic_friendly: "No", allergens: ["Peanuts"] },
  { name: "Til + Gur", type: "dessert", calorie_range: "200-260", calories: 230, protein: 7, carbs: 22, fats: 12, fiber: 6, vegetarian: "Yes", diabetic_friendly: "No", allergens: ["Sesame"] },
  { name: "Coconut + Gur", type: "dessert", calorie_range: "250-330", calories: 290, protein: 4, carbs: 30, fats: 16, fiber: 5, vegetarian: "Yes", diabetic_friendly: "No", allergens: [] },
  { name: "Chia + Milk + Honey", type: "dessert", calorie_range: "200-260", calories: 230, protein: 8, carbs: 22, fats: 10, fiber: 7, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Milk"] },
  { name: "Flaxseed + Gur", type: "dessert", calorie_range: "180-240", calories: 210, protein: 6, carbs: 20, fats: 11, fiber: 7, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Boiled Corn + Honey", type: "dessert", calorie_range: "180-240", calories: 210, protein: 6, carbs: 30, fats: 3, fiber: 4, vegetarian: "Yes", diabetic_friendly: "No", allergens: [] },
  { name: "Pumpkin + Gur", type: "dessert", calorie_range: "150-200", calories: 170, protein: 2, carbs: 35, fats: 0, fiber: 5, vegetarian: "Yes", diabetic_friendly: "No", allergens: [] },
  { name: "Lauki + Milk + Gur", type: "dessert", calorie_range: "160-220", calories: 190, protein: 6, carbs: 30, fats: 4, fiber: 4, vegetarian: "Yes", diabetic_friendly: "No", allergens: ["Milk"] },
  { name: "Chhena + Fruit Bowl", type: "dessert", calorie_range: "200-260", calories: 230, protein: 13, carbs: 20, fats: 10, fiber: 3, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Milk"] },
  { name: "Homemade Low Sugar Payesh", type: "dessert", calorie_range: "180-240", calories: 210, protein: 6, carbs: 30, fats: 6, fiber: 2, vegetarian: "Yes", diabetic_friendly: "No", allergens: ["Milk"] },
  { name: "Low Sugar Mishti Doi", type: "dessert", calorie_range: "150-220", calories: 190, protein: 7, carbs: 28, fats: 5, fiber: 0, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Milk"] },
  { name: "Dark Chocolate + Almond", type: "dessert", calorie_range: "200-260", calories: 230, protein: 6, carbs: 20, fats: 14, fiber: 4, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Nuts"] },
  { name: "Cocoa + Banana", type: "dessert", calorie_range: "220-300", calories: 250, protein: 6, carbs: 38, fats: 8, fiber: 5, vegetarian: "Yes", diabetic_friendly: "No", allergens: [] },
  { name: "Golden Milk + Honey", type: "dessert", calorie_range: "150-200", calories: 170, protein: 7, carbs: 20, fats: 5, fiber: 0, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Milk"] },
  { name: "Almond Milk + Dates", type: "dessert", calorie_range: "180-240", calories: 210, protein: 6, carbs: 28, fats: 9, fiber: 4, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Nuts"] },
  { name: "Chire + Banana + Honey", type: "dessert", calorie_range: "250-330", calories: 290, protein: 7, carbs: 50, fats: 5, fiber: 5, vegetarian: "Yes", diabetic_friendly: "No", allergens: [] },
  { name: "Chire + Yogurt + Fruit", type: "dessert", calorie_range: "220-280", calories: 250, protein: 9, carbs: 40, fats: 4, fiber: 5, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Milk"] },
  { name: "Sprouts + Banana", type: "dessert", calorie_range: "250-330", calories: 300, protein: 11, carbs: 45, fats: 3, fiber: 8, vegetarian: "Yes", diabetic_friendly: "No", allergens: [] },
  { name: "Mixed Sprouts + Honey", type: "dessert", calorie_range: "200-260", calories: 230, protein: 11, carbs: 32, fats: 3, fiber: 8, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: [] },
  { name: "Banana + Sesame + Honey", type: "dessert", calorie_range: "220-300", calories: 250, protein: 7, carbs: 38, fats: 8, fiber: 6, vegetarian: "Yes", diabetic_friendly: "No", allergens: ["Sesame"] },
  { name: "Coconut + Banana + Honey", type: "dessert", calorie_range: "260-340", calories: 300, protein: 5, carbs: 40, fats: 14, fiber: 6, vegetarian: "Yes", diabetic_friendly: "No", allergens: [] },
  { name: "Peanut + Cocoa + Dates", type: "dessert", calorie_range: "260-340", calories: 300, protein: 11, carbs: 32, fats: 15, fiber: 6, vegetarian: "Yes", diabetic_friendly: "No", allergens: ["Peanuts"] },
  { name: "Oats + Cocoa + Milk", type: "dessert", calorie_range: "230-300", calories: 260, protein: 10, carbs: 40, fats: 7, fiber: 5, vegetarian: "Yes", diabetic_friendly: "No", allergens: ["Milk"] },
  { name: "Low Sugar Rasgulla (store-bought)", type: "dessert", calorie_range: "120-180", calories: 150, protein: 6, carbs: 20, fats: 4, fiber: 0, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Milk"] },
  { name: "Baked Sandesh (store-bought)", type: "dessert", calorie_range: "150-220", calories: 190, protein: 9, carbs: 18, fats: 8, fiber: 1, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Milk"] },
  { name: "Sugar-free Mishti Doi (store-bought)", type: "dessert", calorie_range: "130-180", calories: 160, protein: 7, carbs: 22, fats: 4, fiber: 0, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Milk"] },
  { name: "Protein Yogurt Dessert (store)", type: "dessert", calorie_range: "180-240", calories: 210, protein: 15, carbs: 20, fats: 6, fiber: 2, vegetarian: "Yes", diabetic_friendly: "Yes", allergens: ["Milk"] },
  { name: "Date Ladoo (store)", type: "dessert", calorie_range: "200-260", calories: 230, protein: 4, carbs: 30, fats: 10, fiber: 4, vegetarian: "Yes", diabetic_friendly: "No", allergens: ["Nuts"] },
  { name: "Peanut Chikki (low sugar store)", type: "dessert", calorie_range: "180-260", calories: 220, protein: 8, carbs: 20, fats: 12, fiber: 3, vegetarian: "Yes", diabetic_friendly: "No", allergens: ["Peanuts"] },
  { name: "Til Ladoo (store)", type: "dessert", calorie_range: "200-260", calories: 230, protein: 7, carbs: 22, fats: 12, fiber: 5, vegetarian: "Yes", diabetic_friendly: "No", allergens: ["Sesame"] },
];

async function seed() {
  await mongoose.connect(process.env.MONGO_URI);
  console.log("Connected to MongoDB");

  await Meal.deleteMany({});
  console.log("Cleared existing meals");

  const docs = RAW_MEALS.map(m => ({ ...m, allergens: norm(m.allergens) }));
  await Meal.insertMany(docs);
  console.log(`Inserted ${docs.length} meals`);

  await mongoose.disconnect();
  console.log("Done");
}

seed().catch(err => { console.error(err); process.exit(1); });
